name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Front
      run: |
        cd ./front
        npm install
        npm run build
        cd ..
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag matbabs/docktor
    - name: Docker Hub Login
      run: docker login -u matbabs -p $DOCKER_HUB_TOKEN
    - name: Docker Hub Publish
      run: docker push matbabs/docktor
    
